config/routes.rb
SnowSchoolers::Application.routes.draw do
  resources :beta_users

  root to: "lessons#new"

  resources :lesson_times

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :lessons
  put   'lessons/:id/set_instructor'      => 'lessons#set_instructor',      as: :set_instructor
  put   'lessons/:id/remove_instructor'   => 'lessons#remove_instructor',   as: :remove_instructor
  patch 'lessons/:id/confirm_lesson_time' => 'lessons#confirm_lesson_time', as: :confirm_lesson_time
  get   'lessons/:id/complete'            => 'lessons#complete',            as: :complete_lesson
end

app/models/beta_user.rb
class BetaUser < ActiveRecord::Base
end

app/controllers/beta_users_controller.rb
class BetaUsersController < ApplicationController
  before_action :set_beta_user, only: [:show, :edit, :update, :destroy]

  # GET /beta_users
  # GET /beta_users.json
  def index
    @beta_users = BetaUser.all
  end

  # GET /beta_users/1
  # GET /beta_users/1.json
  def show
  end

  # GET /beta_users/new
  def new
    @beta_user = BetaUser.new
  end

  # GET /beta_users/1/edit
  def edit
  end

  # POST /beta_users
  # POST /beta_users.json
  def create
    @beta_user = BetaUser.new(beta_user_params)

    respond_to do |format|
      if @beta_user.save
        format.html { redirect_to root_path, notice: 'Thanks for signing up!' }
        format.json { render action: 'show', status: :created, location: @beta_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @beta_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beta_users/1
  # PATCH/PUT /beta_users/1.json
  def update
    respond_to do |format|
      if @beta_user.update(beta_user_params)
        format.html { redirect_to @beta_user, notice: 'Beta user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beta_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beta_users/1
  # DELETE /beta_users/1.json
  def destroy
    @beta_user.destroy
    respond_to do |format|
      format.html { redirect_to beta_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beta_user
      @beta_user = BetaUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beta_user_params
      params.require(:beta_user).permit(:email, :user_type)
    end
end

app/helpers/beta_users_helper.rb
module BetaUsersHelper
end

app/views/beta_users/_form.html.erb
<%= semantic_form_for @beta_user do |f| %>
  <%= f.inputs do %>
    <%= f.input :email %>
    <%= f.input :user_type %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/beta_users/edit.html.erb
<h1>Editing beta_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @beta_user %> |
<%= link_to 'Back', beta_users_path %>

app/views/beta_users/index.html.erb
<h1>Listing beta_users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beta_users.each do |beta_user| %>
      <tr>
        <td><%= beta_user.email %></td>
        <td><%= beta_user.user_type %></td>
        <td><%= link_to 'Show', beta_user %></td>
        <td><%= link_to 'Edit', edit_beta_user_path(beta_user) %></td>
        <td><%= link_to 'Destroy', beta_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beta user', new_beta_user_path %>

app/views/beta_users/new.html.erb
<img id="cycle-loader" src="/assets/spinner.gif" alt="loader" />

<ul id="slider">
  <li>
    <!-- <img src="/assets/demo/slider/thredbo-village-resort-hero.jpg" class="bg-photo" alt="" /> -->
    <img src="/assets/demo/slider/thredbo1.jpg" class="bg-photo" alt="" />

    <div class="caption col-md-10 col-md-offset-2">
      <div class="block">
        <h1>STAY IN TOUCH</h1>
      </div>

      <div class="block">
      </div>

        <%= form_for(@beta_user) do |f| %>
          <% if @beta_user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@beta_user.errors.count, "error") %> prohibited this beta_user from being saved:</h2>
              <ul>
              <% @beta_user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="col-md-6 email-input">
            <%= f.email_field :email, autofocus: true, class:"black-text input-group input-group-lg", placeholder:"Enter Email"  %>
             <!-- <%= f.select :user_type, options_for_select(['Interested in taking lessons', 'Interested in teaching']), class: "col-md-4 black-text " %> -->
             <br>
             <br>
<%= f.submit "Sign up", class:"btn btn-signup btn-lg" %>
          </div>
          <div class="col-md-6">
          </div>
        <% end %>
    </div>
  </li>
</ul>

<!-- %= render "devise/shared/links" %> -->

app/views/beta_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @beta_user.email %>
</p>

<p>
  <strong>User type:</strong>
  <%= @beta_user.user_type %>
</p>

<%= link_to 'Edit', edit_beta_user_path(@beta_user) %> |
<%= link_to 'Back', beta_users_path %>