config/routes.rb
SnowSchoolers::Application.routes.draw do
  resources :beta_users

  root to: "lessons#new"

  resources :lesson_times

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :lessons
  put   'lessons/:id/set_instructor'      => 'lessons#set_instructor',      as: :set_instructor
  put   'lessons/:id/remove_instructor'   => 'lessons#remove_instructor',   as: :remove_instructor
  patch 'lessons/:id/confirm_lesson_time' => 'lessons#confirm_lesson_time', as: :confirm_lesson_time
  get   'lessons/:id/complete'            => 'lessons#complete',            as: :complete_lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :requester, class_name: 'User', foreign_key: 'requester_id'
  belongs_to :instructor, class_name: 'User', foreign_key: 'instructor_id'
  belongs_to :lesson_time
  has_and_belongs_to_many :previous_experiences
  has_many :students
  accepts_nested_attributes_for :students, reject_if: :all_blank, allow_destroy: true

  validates :activity, :location, :lesson_time, presence: true
  validates :objectives, :duration, :start_time, :experience_level, :previous_experiences, 
            presence: true, on: :update
  validates :gear, inclusion: { in: [true, false] }, on: :update
  validates :terms_accepted, inclusion: { in: [true], message: 'must accept terms' }, on: :update
  validates :actual_start_time, :actual_end_time, presence: true, if: :just_finalized?
  validate :instructors_must_be_available, unless: :no_instructors_post_instructor_drop?
  validate :requester_must_not_be_instructor, on: :create
  validate :lesson_time_must_be_valid
  validate :student_exists, on: :update

  after_create :send_lesson_request_to_instructors
  before_save :calculate_actual_lesson_duration, if: :just_finalized?

  def date
    lesson_time.date
  end

  def slot
    lesson_time.slot
  end

  def active?
    active_states = ['new', 'booked', 'confirmed', 'pending instructor', 'pending requester']
    active_states.include?(state)
  end

  def new?
    state == 'new'
  end

  def canceled?
    state == 'canceled'
  end

  def pending_instructor?
    state == 'pending instructor'
  end

  def pending_requester?
    state == 'pending requester'
  end

  def finalizing?
    state == 'finalizing'
  end

  def waiting_for_payment?
    state == 'waiting for payment'
  end

  def available_instructors
    User.instructors - Lesson.booked_instructors(lesson_time)
  end

  def available_instructors?
    available_instructors.any?
  end

  def get_changed_attributes(original_lesson)
    lesson_changes = self.previous_changes
    lesson_time_changes = self.lesson_time.attributes.diff(original_lesson.lesson_time.attributes)
    changed_attributes = lesson_changes.merge(lesson_time_changes)
    changed_attributes.reject { |attribute, change| ['updated_at', 'id', 'state', 'lesson_time_id'].include?(attribute) }
  end

  def self.find_lesson_times_by_requester(user)
    self.where('requester_id = ?', user.id).map { |lesson| lesson.lesson_time }
  end

  def self.booked_instructors(lesson_time)
    booked_lessons = lesson_time.slot == 'Full Day' ? self.find_all_booked_lessons_in_day(lesson_time) : self.find_booked_lessons(lesson_time)
    booked_lessons.any? ? booked_lessons.map { |lesson| User.find(lesson.instructor_id) } : []
  end

  def self.find_booked_lessons(lesson_time)
    self.where('lesson_time_id = ? AND instructor_id is not null', lesson_time.id)
  end

  def self.find_all_booked_lessons_in_day(full_day_lesson_time)
    morning_lesson_time = LessonTime.find_morning_slot(full_day_lesson_time.date)
    afternoon_lesson_time = LessonTime.find_afternoon_slot(full_day_lesson_time.date)
    full_day_booked_lessons = self.find_booked_lessons(full_day_lesson_time)
    morning_booked_lessons = self.find_booked_lessons(morning_lesson_time) if morning_lesson_time
    afternoon_booked_lessons = self.find_booked_lessons(afternoon_lesson_time) if afternoon_lesson_time
    [full_day_booked_lessons, morning_booked_lessons, afternoon_booked_lessons].flatten
  end

  private

  def instructors_must_be_available
    errors.add(:instructor, "not available") unless available_instructors.any?
  end

  def requester_must_not_be_instructor
    errors.add(:instructor, "cannot request a lesson") if self.requester.instructor?
  end

  def lesson_time_must_be_valid
    errors.add(:lesson_time, "invalid") unless lesson_time.valid?
  end

  def student_exists
    errors.add(:students, "count must be greater than zero") unless students.any?
  end

  def send_lesson_request_to_instructors
    LessonMailer.send_lesson_request_to_instructors(self).deliver
  end

  def calculate_actual_lesson_duration
    start_time = Time.parse(actual_start_time)
    end_time = Time.parse(actual_end_time)
    self.actual_duration = (end_time - start_time)/3600
  end

  def just_finalized?
    waiting_for_payment?
  end

  def no_instructors_post_instructor_drop?
    pending_requester?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  respond_to :html

  skip_before_filter :authenticate_user!, only: [:new, :create]
  before_filter :save_lesson_params_and_redirect, only: :create
  before_filter :create_lesson_from_session

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
    @lesson_time = @lesson.lesson_time
  end

  def create
    create_lesson_and_redirect
  end

  def complete
    @lesson = Lesson.find(params[:id])
    @lesson_time = @lesson.lesson_time
    @state = 'booked'
    flash.now[:notice] = "You're almost there! We just need a few more details."
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @lesson_time = @lesson.lesson_time
    @state = @lesson.instructor ? 'pending instructor' : 'booked'
  end

  def update
    @lesson = Lesson.find(params[:id])
    @original_lesson = @lesson.dup
    @lesson.assign_attributes(lesson_params)
    @lesson.previous_experiences = format_previous_experiences
    @lesson.lesson_time = @lesson_time = LessonTime.find_or_create_by(lesson_time_params)
    @lesson.save ? send_lesson_update_notice_to_instructor : determine_update_state
    respond_with @lesson
  end

  def show
    @lesson = Lesson.find(params[:id])
    check_user_permissions
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.update(state: 'canceled')
    send_cancellation_email_to_instructor
    flash[:notice] = 'Your lesson has been canceled.'
    redirect_to root_path
  end

  def set_instructor
    @lesson = Lesson.find(params[:id])
    @lesson.instructor = current_user
    @lesson.update(state: 'confirmed')
    if @lesson.state =='booked'
      LessonMailer.send_lesson_confirmation(@lesson).deliver
    end
    redirect_to @lesson
  end

  def remove_instructor
    @lesson = Lesson.find(params[:id])
    @lesson.instructor = nil
    @lesson.update(state: @lesson.available_instructors? ? 'new' : 'pending requester')
    send_instructor_cancellation_emails
    redirect_to @lesson
  end

  def confirm_lesson_time
    @lesson = Lesson.find(params[:id])
    @lesson.update(lesson_params.merge(state: 'waiting for payment'))
    @lesson.state = @lesson.valid? ? 'waiting for payment' : 'confirmed'
    LessonMailer.send_payment_email_to_requester(@lesson).deliver
    respond_with @lesson, action: :show
  end

  private

  def save_lesson_params_and_redirect
    unless current_user
      flash[:alert] = 'You need to sign in or sign up before continuing.'
      session[:lesson] = params[:lesson]
      redirect_to new_user_session_path and return
    end
  end

  def create_lesson_from_session
    return unless current_user && session[:lesson]
    params[:lesson] = session.delete(:lesson)
    create_lesson_and_redirect
  end

  def create_lesson_and_redirect
    @lesson = Lesson.new(lesson_params)
    @lesson.requester = current_user
    @lesson.lesson_time = @lesson_time = LessonTime.find_or_create_by(lesson_time_params)
    @lesson.save ? (redirect_to complete_lesson_path(@lesson)) : (render :new)
  end

  def send_cancellation_email_to_instructor
    if @lesson.instructor.present?
      LessonMailer.send_cancellation_email_to_instructor(@lesson).deliver
    end
  end

  def send_instructor_cancellation_emails
    LessonMailer.send_lesson_request_to_instructors(@lesson, @lesson.instructor).deliver if @lesson.available_instructors?
    LessonMailer.inform_requester_of_instructor_cancellation(@lesson, @lesson.available_instructors?).deliver
  end

  def send_lesson_update_notice_to_instructor
    if @lesson.instructor.present?
      changed_attributes = @lesson.get_changed_attributes(@original_lesson)
      return unless changed_attributes.any?

      if @lesson.available_instructors.include?(@lesson.instructor)
        LessonMailer.send_lesson_update_notice_to_instructor(@original_lesson, @lesson, changed_attributes).deliver
      else
        @lesson.instructor = nil
        @lesson.update(state: @lesson.available_instructors? ? 'new' : 'pending requester')
        send_instructor_cancellation_emails
      end
    end
  end

  def check_user_permissions
    unless current_user && (current_user == @lesson.requester || current_user.instructor?)
      flash[:alert] = "You do not have access to this page."
      redirect_to root_path
    end
  end

  def format_previous_experiences
    previous_experience_ids = params[:lesson][:previous_experience_ids].reject(&:blank?)
    previous_experience_ids.map { |id| PreviousExperience.find(id) }
  end

  def determine_update_state
    @lesson.state = 'new' unless params[:lesson][:terms_accepted] == '1'
    if @lesson.state == 'new'
      flash[:alert] = "Lesson could not be updated."
    end
    @state = params[:lesson][:state]
  end

  def lesson_params
    params.require(:lesson).permit(:activity, :location, :state, :student_count, :gear, :objectives, :duration,
      :start_time, :actual_start_time, :actual_end_time, :experience_level, :terms_accepted,
      students_attributes: [:id, :name, :age_range, :gender, :relationship_to_requester, :_destroy])
  end

  def lesson_time_params
    params[:lesson].require(:lesson_time).permit(:date, :slot)
  end
end

app/views/lessons/_full_form.html.erb
<div id="middle" class="container">
  <div class="white">

    <header class="page-header">
      <h1>Update Your Lesson</h1>
    </header>

    <%= semantic_form_for @lesson do |f| %>
      <%= f.semantic_errors :instructor %>
      <div class='row'>
        <div class="col-md-6">
          <h4>Basic <strong>Info</strong></h4>

          <div class='row'>
            <div class="col-md-6">
              <label>Lesson Type</label>
              <%= f.input :activity, as: :select, collection: ['Ski', 'Snowboard'], include_blank: 'Lesson Type', label: false %>
            </div>

            <div class="col-md-6">
              <label>Mountain</label>
                <%= f.input :location, as: :select, collection: ['Thredbo', 'Perisher', 'Mt. Buller', 'Mt. Hotham', 'Falls Creek'], include_blank: 'Mountain', label: false %>
            </div>
          </div>

          <%= f.semantic_fields_for :lesson_time, @lesson_time do |lt_f| %>
            <div class='row'>
              <div class="col-md-6">
                <label>Date</label>
                <%= lt_f.input :date, as: :string, input_html: { id: 'datepicker' }, placeholder: 'Pick a date', label: false %>
                <span class="search-area-icon"></span>
              </div>

              <div class="col-md-6">
                <label>Slot</label>
                <%= lt_f.input :slot, as: :select, collection: ['Morning', 'Afternoon', 'Full Day'], include_blank: 'Length', label: false %>
              </div>
            </div>
          <% end %>

          <div class='row'>
            <div class="col-md-4">
              <label>Duration</label>
              <%= f.input :duration, as: :select, collection: [['2 hours', 2], ['3 hours', 3], ['6 hours', 6]], include_blank: 'Duration', label: false %>
            </div>

            <div class="col-md-4">
              <label>Start Time</label>
              <%= f.input :start_time, as: :string, input_html: { id: 'timepicker' }, placeholder: 'Pick a start time', label: false %>
            </div>

            <div class="col-md-4">
              <label>Do you have gear?</label>
              <%= f.input :gear, as: :select, collection: [['Yes', true], ['No', false]], include_blank: 'Gear', label: false %>
            </div>
          </div>

          <h4>Student <strong>Info</strong></h4>

          <div id='lesson_students_input'>
            <%= f.semantic_fields_for :students do |student| %>
              <%= render 'student_fields', f: student %>
            <% end %>
            <div class='links'>
              <%= link_to_add_association 'Add Student', f, :students %>
            </div>
            <%= f.semantic_errors :students %>
          </div>
        </div>

        <div class="col-md-6">
          <h4>Objectives <strong> and Experience</strong></h4>

          <div class='col-md-12'>
            <label>Objectives</label>
            <%= f.input :objectives, placeholder: 'What do you hope to get out of this lesson?', label: false %>
          </div>

          <div class='col-md-12'>
            <label>Experience Level</label>
            <%= f.input :experience_level, as: :select, collection: [['First time on the mountain', 0], ['Beginner (~skier type I)', 1], ['Intermediate (~skier type II)', 2], ['Advanced (~skier type III)', 3]], include_blank: 'How comfortable are you on the mountain?', label: false %>
          </div>

          <div class='col-md-12'>
            <label>Previous Experience</label>
            <%= f.input :previous_experiences, as: :check_boxes, label: false %>
          </div>
        </div>
      </div>

      <hr class='lesson-break' />

      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
          <div class="col-md-9">
            <span class="remember-box checkbox pull-right">
              <label for="rememberme">
                <% if @lesson.new? %>
                  <%= f.check_box :terms_accepted, id: "rememberme" %>I agree to the <span><a href="#">Terms and Conditions</a></span>
                <% else %>
                  <%= f.input :terms_accepted, as: :hidden, input_html: { value: true } %>
                <% end %>
              </label>
            </span>
          </div>
          <div class="col-md-3">
            <%= f.input :state, as: :hidden, input_html: { value: @state } %>
            <%= f.submit "UPDATE", class: 'btn sign-up-btn pull-right' %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

<!-- SLIDER -->
<img id="cycle-loader" src="/assets/spinner.gif" alt="loader" />

<ul id="slider">
  <li><img src="/assets/demo/slider/powdery-mountain.jpg" alt="" /></li>
  <li><img src="/assets/demo/slider/ski-1.jpg" alt="" /></li>
</ul>
<!-- /SLIDER

app/views/lessons/_lesson_actions_active.html.erb
<div class='active-actions'>
  <% if current_user.instructor? && @lesson.instructor.nil? %>
    <%= button_to "Accept this Lesson Request", set_instructor_path, method: :put, class: "btn btn-success" %>
  <% end %>

  <% if current_user == @lesson.instructor %>
    <% if @lesson.pending_instructor? %>
      <%= button_to "Confirm Updates", set_instructor_path, method: :put, class: "btn btn-default" %>
    <% end %>
    <%= button_to "Drop It", remove_instructor_path, method: :put, class: "btn btn-warning" %>
  <% end %>

  <% if current_user == @lesson.requester %>
    <%= link_to 'Edit Lesson', edit_lesson_path(@lesson) %>
    <%= link_to 'Cancel Lesson', @lesson, method: :delete, class: "btn btn-warning" %>
  <% end %>
</div>

app/views/lessons/_lesson_actions_confirmed.html.erb
<% if current_user == @lesson.instructor %>
  <%= semantic_form_for @lesson, url: confirm_lesson_time_path do |f| %>
    <%= f.input :actual_start_time, as: :string, input_html: { id: 'start-timepicker' } %>
    <%= f.input :actual_end_time, as: :string, input_html: { id: 'end-timepicker' } %>
    <%= f.actions %>
  <% end %>
<% else %>
  Waiting for instructor to confirm lesson start and end times.
<% end %>

app/views/lessons/_lesson_actions_finalizing.html.erb
<% if current_user == @lesson.instructor %>
  <%= semantic_form_for @lesson, url: confirm_lesson_time_path do |f| %>
    <%= f.input :actual_start_time, as: :string, input_html: { id: 'start-timepicker' } %>
    <%= f.input :actual_end_time, as: :string, input_html: { id: 'end-timepicker' } %>
    <%= f.actions %>
  <% end %>
<% else %>
  Waiting for instructor to confirm lesson start and end times.
<% end %>

app/views/lessons/_lesson_actions_unconfirmed.html.erb
<% if current_user.instructor? && @lesson.instructor.nil? %>
  <%= button_to "Take It", set_instructor_path, method: :put %>
<% end %>

<% if current_user == @lesson.instructor %>
  <% if @lesson.pending_instructor? %>
    <%= button_to "Confirm Updates", set_instructor_path, method: :put %>
  <% end %>
  <%= button_to "Drop It", remove_instructor_path, method: :put %>
<% end %>

<% if current_user == @lesson.requester %>
  <%= link_to 'Edit Lesson', edit_lesson_path(@lesson) %>
  <%= link_to 'Cancel Lesson', @lesson, method: :delete %>
<% end %>

app/views/lessons/_lesson_details.html.erb
<p>Requester: <%= @lesson.requester.name %></p>

<% if @lesson.instructor %>
  <p>Instructor: <%= @lesson.instructor.name %></p>
<% else %>
  <% if @lesson.pending_requester? %>
    <p>No instructors available for this date and time. Please edit or cancel.</p>
  <% else %>
    <p>No instructor assigned yet.</p>
  <% end %>
<% end %>

<div class='row'>
  <div class="col-md-6">
    <h4>Basic <strong>Info</strong></h4>
    
    <div class='row'>
      <div class="col-md-6">
        <label>Lesson Type:</label>
        <div class='form-control'><%= @lesson.activity %></div>
      </div>

      <div class="col-md-6">
        <label>Mountain:</label>
        <div class='form-control'><%= @lesson.location %></div>
      </div>
    </div>

      <div class='row'>
        <div class="col-md-6">
          <label>Date:</label>
          <div class='form-control'><%= @lesson.date %></div>
        </div>

        <div class="col-md-6">
          <label>Slot:</label>
          <div class='form-control'><%= @lesson.slot %></div>
        </div>
      </div>

    <div class='row'>
      <div class="col-md-4">
        <label>Duration:</label>
        <div class='form-control'><%= "#{@lesson.duration} hours" if @lesson.duration %></div>
      </div>

      <div class="col-md-4">
        <label>Start Time:</label>
        <div class='form-control'><%= @lesson.start_time %></div>
      </div>

      <div class="col-md-4">
        <label>Do you have gear?</label>
        <div class='form-control'><%= @lesson.gear? ? 'Yes' : 'No' %></div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <h4>Objectives <strong> and Experience</strong></h4>

    <div class='col-md-12'>
      <label>Objectives:</label>
      <div class='form-control'><%= @lesson.objectives %></div>
    </div>

    <div class='col-md-12'>
      <label>Experience Level:</label>
      <div class='form-control'><%= @lesson.experience_level.to_s %></div>
    </div>

    <div class='col-md-12'>
      <label>Previous Experience:</label>
      <div class='form-control'><%= @lesson.previous_experiences.map(&:name).join(', ') %></div>
    </div>
  </div>
</div>

app/views/lessons/_student_fields.html.erb
<div class='nested-fields student-box'>
  <%= f.inputs do %>
    <div class='row'>
      <div class='col-md-6'>
        <label>Student Name</label>
        <span class='remove-student'>(<%= link_to_remove_association "Remove Student", f, class: 'remove-student' %>)</span>
        <%= f.input :name, placeholder: "Full name of student", label: false %>
      </div>
      <div class='col-md-3'>
        <label>Age Range</label>
        <%= f.input :age_range, as: :select, collection: ['3-10', '11-20', '21-30', '31-40', '41 and up'], include_blank: 'Age Range', label: false %>
      </div>
      <div class='col-md-3'>
        <label>Gender</label>
        <%= f.input :gender, as: :select, collection: ['Male', 'Female'], include_blank: 'Gender', label: false %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <label>Relationship to Requester</label>
        <%= f.input :relationship_to_requester, as: :select, collection: ['Me', 'Child', 'Friend', 'Spouse', 'Other'], include_blank: 'How is this student related to you?', label: false %>
      </div>
    </div>
  <% end %>
</div>

app/views/lessons/complete.html.erb
<%= render partial: 'full_form' %>

app/views/lessons/edit.html.erb
<%= render partial: 'full_form' %>

app/views/lessons/index.html.erb
<h1>[ADMIN ONLY] List of all lessons</h1>

<table>
  <thead>
    <tr>
      <th>Lesson Link</th>
      <th>Time Stamp</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to lesson.id, lesson %></td>
        <td><%= lesson.created_at %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beta user', new_beta_user_path %>

app/views/lessons/new.html.erb
<!-- SLIDER -->
<img id="cycle-loader" src="/assets/spinner.gif" alt="loader" />

<ul id="slider">
  <li>
    <!-- <img src="/assets/demo/slider/thredbo-village-resort-hero.jpg" class="bg-photo" alt="" /> -->
    <img src="/assets/demo/slider/thredbo1.jpg" class="bg-photo" alt="" />
    <div class="caption">

      <div class="block">
        <h1>BOOK A LESSON TODAY</h1>
      </div>

      <div class="block">
        <p>Personalized one-on-one attention from an expert <strong>Snow Schoolers </strong> instructor is the best way to experience the Snowies!</p>
      </div>

      <%= semantic_form_for @lesson do |f| %>
        <%= f.semantic_errors :instructor %>
          <div class="block inputs">
            <p>
              <div class="col-md-3">
                <%= f.input :activity, as: :select, collection: ['Ski', 'Snowboard'], include_blank: 'Lesson Type', label: false %>
              </div>

              <div class="col-md-3">
                <%= f.input :location, as: :select, collection: ['Thredbo', 'Perisher', 'Mt. Buller', 'Mt. Hotham', 'Falls Creek'], include_blank: 'Mountain', label: false %>
              </div>

              <%= f.semantic_fields_for :lesson_time, @lesson_time do |lt_f| %>
                <div class="col-md-3">
                  <%= lt_f.input :date, as: :string, input_html: { id: 'datepicker' }, placeholder: 'Date', label: false %>
                  <span class="search-area-icon"></span>
                </div>

                <div class="col-md-3">
                  <%= lt_f.input :slot, as: :select, collection: ['Morning', 'Afternoon', 'Full Day'], include_blank: 'Length', label: false %>
                </div>
              <% end %>
            </p>
          </div>

        <%= f.input :state, as: :hidden, input_html: { value: 'new' } %>

        <div class="block">
          <%= f.actions do %>
            <%= f.action :submit, as: :input, button_html: { class: 'btn btn-info', value: 'Book Lesson' } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </li>
  <li><img src="/assets/demo/slider/happy.jpg" alt="" /></li>
</ul>
<!-- /SLIDER -->

app/views/lessons/show.html.erb
<div id="middle" class="container">
  <div class="white">

    <header class="page-header">
      <h1>Lesson Details</h1>
    </header>

    <%= render partial: 'lesson_details' %>

    <% if @lesson.active? %>
      <%= render partial: 'lesson_actions_active' %>
    <% end %>

    <% if @lesson.finalizing? %>
      <%= render partial: 'lesson_actions_finalizing' %>
    <% end %>

    <% if @lesson.canceled? %>
      <p>Lesson has been canceled.</p>
    <% end %>

  </div>
</div>

<!-- SLIDER -->
<img id="cycle-loader" src="/assets/spinner.gif" alt="loader" />

<ul id="slider">
  <li><img src="/assets/demo/slider/snow-less.jpg" alt="" /></li>
  <li><img src="/assets/demo/slider/ski-1.jpg" alt="" /></li>
</ul>
<!-- /SLIDER